version: "3"
services:
  test_database:
    container_name: mysql8.0.30
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: testDB
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
